listen: "0.0.0.0:8080"
upstreams:
  - host: "localhost"
    port: 9001
timeouts:
  connect_ms: 6000
  read_ms: 15000
  write_ms: 15000
  total_ms: 3000000
limits:
  max_client_conns: 3000
  max_conns_per_upstream: 300
logging:
  level: "info"